services:
  - type: web
    name: youtube-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: ${{TELEGRAM_BOT_TOKEN}}  # From Render secrets
      - key: WEBHOOK_URL
        value: ${{WEBHOOK_URL}}  # From Render secrets
      - key: CHANNEL_USERNAME
        value: "atheraber"  # Your channel
