services:
  - type: web
    name: youtube-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -c "from bot import set_webhook; set_webhook()"
    startCommand: "uvicorn bot:webserver --host 0.0.0.0 --port 10000"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
      - key: APP_URL
        value: https://youtube-bot-3-1g9w.onrender.com
      - key: CHANNEL_USERNAME
        value: "atheraber"
      - key: WEBHOOK_PATH
        value: "/webhook/telegram"
      - key: WEBHOOK_URL
        value: f"{APP_URL}{WEBHOOK_PATH}"
