services:
  - type: web
    name: youtube-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -c "from bot import set_webhook; set_webhook()"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
      - key: WEBHOOK_URL
        value: https://youtube-bot-3-1g9w.onrender.com
      - key: CHANNEL_USERNAME
        value: "atheraber"
      - key: SESSION_SECRET
        value: ${{SESSION_SECRET}}  # For Flask sessions
      - key: WEBHOOK_PATH
        value: "/webhook/telegram"
